
name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.PAGES }}
          branch: master
          folder: dist
          repository-name: Botode/Botode.github.io
          clean: true
